# defaults to 50826 if not set
Port: 50831

# server listening for host
Host: 0.0.0.0

# starts http and/or https server
EnableHTTP: true
EnableHTTPS: true # NOTE: missing cert

Devices:
  - Host: pi-bed
    Port: 50826 # NOTE: 50826 is the default pirgb-server port (optional)
  - Host: pi-lr
  - Host: pi-bath
  - Host: pi-kitchen

Groups:
  - Name: All
    Sections:
      - "*"
